import type {Metadata} from 'next'
import './globals.css'
import {Analytics} from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: 'Trang web của An',
  description: 'Generated by create next app',
  openGraph: {
    title: "An's website",
    description: "Chia sẽ những kinh nghiệm, sở thích của bạn An",
    type: 'website',
    images: ['https://blog-web-henna.vercel.app/images/my-image.jpg']
  }
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body
          // className={inter.className}
      >{children}
      <Analytics/>
      <SpeedInsights/>
      </body>
      </html>
  )
}
